# Generated by Django 4.1.7 on 2023-04-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('city', models.CharField(max_length=255, verbose_name='Ваш населённый пункт')),
                ('appeal_text', models.TextField(blank=True, verbose_name='Текст обращения')),
                ('e_mail', models.EmailField(blank=True, max_length=254, verbose_name='Электронный адрес для связи')),
                ('phone_number', models.IntegerField(blank=True, verbose_name='Телефонный номер для связи')),
                ('photo', models.ImageField(blank=True, upload_to='photos/appeals/%Y/%m/%d/', verbose_name='Фотография нарушения, если требуется')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Обращения',
                'verbose_name_plural': 'Обращения',
                'ordering': ['time_create', 'name'],
            },
        ),
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('photo', models.ImageField(blank=True, upload_to='photos/articles/%Y/%m/%d/', verbose_name='Фотография')),
                ('photo_2nd', models.ImageField(blank=True, upload_to='photos/articles/%Y/%m/%d/', verbose_name='Фотография2')),
                ('photo_3rd', models.ImageField(blank=True, upload_to='photos/articles/%Y/%m/%d/', verbose_name='Фотография3')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Статьи',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-time_create', 'title'],
            },
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('photo', models.ImageField(blank=True, upload_to='photos/news/%Y/%m/%d/', verbose_name='Фотография')),
                ('photo_2nd', models.ImageField(blank=True, upload_to='photos/news/%Y/%m/%d/', verbose_name='Фотография2')),
                ('photo_3rd', models.ImageField(blank=True, upload_to='photos/news/%Y/%m/%d/', verbose_name='Фотография3')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'ordering': ['-time_create', 'title'],
            },
        ),
    ]
