# Generated by Django 4.1.7 on 2023-04-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронный адрес для связи'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Телефонный номер для связи'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/appeals/%Y/%m/%d/', verbose_name='Фотография нарушения, если требуется'),
        ),
    ]
